import boto3
from langchain.llms.base import LLM
import google.generativeai as genai


class GeminiLLM:
    def __init__(self, api_key: str, model: str = 'gemini-1.5-pro', system_instruction: str = None):
        """
        Initialize the Gemini LLM with API key, model, and system instruction.

        Args:
            api_key (str): Your API key for the Gemini model.
            model (str): The Gemini model version to use (default: 'gemini-1.5-pro').
            system_instruction (str): Optional system-level instruction to guide the model.
        """
        self.api_key = api_key
        self.model = model
        self.system_instruction = system_instruction

        genai.configure(api_key=api_key)

        # Initialize the ChatGoogleGenerativeAI model
        self.llm = genai.GenerativeModel(
            model_name="gemini-1.5-flash",
            system_instruction=system_instruction)
        
        self.generation_config = genai.types.GenerationConfig(
                temperature=1.0
            )

    def call(self, prompt: str) -> str:
        """
        Perform inference with the Gemini model using the provided prompt.
        
        Args:
            prompt (str): The input prompt from the user.

        Returns:
            str: The response generated by the Gemini model.
        """
        # Prepare the messages for the model, including the system instruction if provided

        # Invoke the model with the prepared messages
        try:
            response = self.llm.generate_content(prompt, generation_config=self.generation_config)
            return response.text
        except Exception as e:
            # Log or print the error if necessary
            print(f"Error during inference: {str(e)}")
            return "An error occurred during the inference process."



class BedrockLLM(LLM):
    def __init__(self, model_id: str, region_name: str = "us-west-2"):
        self.client = boto3.client('bedrock-runtime', region_name=region_name)
        self.model_id = model_id

    def call(self, prompt: str, stop=None) -> str:
        response = self.client.invoke_model(
            modelId=self.model_id,
            body=prompt,
            contentType="text/plain"
        )
        return response['body'].read().decode('utf-8')

    @property
    def _llm_type(self) -> str:
        return "bedrock"
    









# bedrock_llm = BedrockLLM(model_id="amazon.titan")

# # Create the same LangChain structure as before
# from langchain.prompts import PromptTemplate
# from langchain.chains import LLMChain

# prompt = PromptTemplate(input_variables=["topic"], template="Explain {topic} in simple terms.")

# chain = LLMChain(llm=bedrock_llm, prompt=prompt)

# result = chain.run(topic="Quantum Computing")
# print(result)



# # Initialize the model with a system instruction
# system_instruction = "You are a concise, formal assistant who specializes in explaining scientific concepts."

# gemini_llm = GeminiLLM(api_key="your_gemini_api_key", system_instruction=system_instruction)

# # Now the system instruction will be automatically applied to every prompt
# user_input = "Explain quantum computing."
# result = gemini_llm._call(user_input)
# print(result)