import boto3
from langchain.llms.base import LLM
import google.generativeai as genai
from config import Config
import json
from botocore.exceptions import ClientError

class BedrockLLM:
    def __init__(self, modelId: str = 'anthropic.claude-3-5-sonnet-20241022-v2:0', system_instruction: str = None):
        """
        Initialize the Gemini LLM with API key, model, and system instruction.

        Args:
            api_key (str): Your API key for the Gemini model.
            model (str): The Gemini model version to use (default: 'gemini-1.5-pro').
            system_instruction (str): Optional system-level instruction to guide the model.
        """
        self.client = boto3.client('bedrock-runtime', aws_access_key_id=Config.AWS_ACCESS_KEY,
                             aws_secret_access_key=Config.AWS_SECRET_ACCESS_KEY,
                      region_name='us-west-2')
        self.modelId = modelId
        self.system_instruction = system_instruction
    

    def call(self, prompt: str) -> str:
        """
        Perform inference with the Gemini model using the provided prompt.
        
        Args:
            prompt (str): The input prompt from the user.

        Returns:
            str: The response generated by the Gemini model.
        """

        # Invoke the model with the prepared messages
        try:
            
            native_request = {
                "anthropic_version": "bedrock-2023-05-31",
                "max_tokens": 4000,
                "temperature": 0.3,
                "system": self.system_instruction,
                "messages": [
                    {
                        "role": "user",
                        "content": [{"type": "text", "text": prompt}],
                    }
                ],
            }

            request = json.dumps(native_request)

            response = self.client.invoke_model(modelId=self.modelId, body=request)

            # Decode the response body.
            model_response = json.loads(response["body"].read())

            # Extract and print the response text.
            response_text = model_response["content"][0]["text"]

            return response_text

        except Exception as e:
            # Log or print the error if necessary
            print(f"Error during inference of Bedrock: {str(e)}")
            print(f"*******************************Fallback Response**************************************")

            fallback_llm = GeminiLLM(api_key=Config.GEMINI_KEY, system_instruction=self.system_instruction)
            fallback_response = fallback_llm.call(prompt)

            return fallback_response

class GeminiLLM:
    def __init__(self, api_key: str, model: str = 'gemini-1.5-pro', system_instruction: str = None):
        """
        Initialize the Gemini LLM with API key, model, and system instruction.

        Args:
            api_key (str): Your API key for the Gemini model.
            model (str): The Gemini model version to use (default: 'gemini-1.5-pro').
            system_instruction (str): Optional system-level instruction to guide the model.
        """
        self.api_key = api_key
        self.model = model
        self.system_instruction = system_instruction

        genai.configure(api_key=api_key)

        # Initialize the ChatGoogleGenerativeAI model
        self.llm = genai.GenerativeModel(
            model_name="gemini-1.5-flash",
            system_instruction=system_instruction)
        
        self.generation_config = genai.types.GenerationConfig(
                temperature=1.0
            )

    def call(self, prompt: str) -> str:
        """
        Perform inference with the Gemini model using the provided prompt.
        
        Args:
            prompt (str): The input prompt from the user.

        Returns:
            str: The response generated by the Gemini model.
        """
        # Prepare the messages for the model, including the system instruction if provided

        # Invoke the model with the prepared messages
        try:
            response = self.llm.generate_content(prompt, generation_config=self.generation_config)
            return response.text
        except Exception as e:
            # Log or print the error if necessary
            print(f"Error during inference: {str(e)}")
            return "An error occurred during the inference process."









# bedrock_llm = BedrockLLM(model_id="amazon.titan")

# # Create the same LangChain structure as before
# from langchain.prompts import PromptTemplate
# from langchain.chains import LLMChain

# prompt = PromptTemplate(input_variables=["topic"], template="Explain {topic} in simple terms.")

# chain = LLMChain(llm=bedrock_llm, prompt=prompt)

# result = chain.run(topic="Quantum Computing")
# print(result)



# # Initialize the model with a system instruction
# system_instruction = "You are a concise, formal assistant who specializes in explaining scientific concepts."

# gemini_llm = GeminiLLM(api_key="your_gemini_api_key", system_instruction=system_instruction)

# # Now the system instruction will be automatically applied to every prompt
# user_input = "Explain quantum computing."
# result = gemini_llm._call(user_input)
# print(result)